title: QuadraticNumberFields
description: >-
  A formalization of quadratic number fields in Lean 4
baseurl: "/QuadraticNumberFields"
url: "https://frankieew.github.io"
repository: FrankieeW/QuadraticNumberFields
github_username: FrankieeW

collections:
  pages:
    output: true
    permalink: /:path

remote_theme: pages-themes/dinky@v0.2.0
plugins:
  - jekyll-remote-theme

defaults:
  - scope:
      path: ""
    values:
      seo_description_max_words: 10

webrick:
  headers:
    Access-Control-Allow-Origin: "*"
