name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-lean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Elan
        run: |
          curl https://elan.lean-lang.org/elan-init.sh -sSf | sh -s -- -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: Build Lean
        working-directory: ./Lean
        run: |
          lake exe cache get
          lake build

  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          working-directory: ./site

      - name: Build site
        working-directory: ./site
        run: |
          bundle exec jekyll build
